# Generated by Django 5.2 on 2026-08-13 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stuffs', '0005_stuff_district'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('issue_date', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('missing', 'missing'), ('discover', 'discover')], default='', max_length=50)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('reward', models.BooleanField(default=False)),
                ('stuff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stuffs.stuff')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
