# Generated by Django 5.2 on 2026-08-12 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('stuffs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stuff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stuffs.stuff'),
        ),
    ]
