# Generated by Django 5.2 on 2026-08-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('posting', 'posting'), ('waiting', 'waiting')], default='', max_length=50),
        ),
    ]
