# Generated by Django 5.2 on 2026-08-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_stuff'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('missing', 'missing'), ('discover', 'discover')], default='', max_length=50),
        ),
    ]
