# Generated by Django 5.2 on 2026-08-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_stuff_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('posting', 'posting'), ('waiting', 'waiting'), ('finished', 'finished')], default='', max_length=50),
        ),
    ]
