# Generated by Django 5.2 on 2026-08-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
