import csv
from datetime import datetime
import os
from dotenv import load_dotenv
import psycopg2
from psycopg2 import sql as pg_sql 

load_dotenv()


def get_connection():
    return psycopg2.connect(
        database="webstestdb",
        user="postgres",
        password="hkhkhk",
        host="localhost",
        port="5432",
    )





def import_data(table, csv_path="data.csv"):
    if not os.path.exists(csv_path):
        print(f"Error: File '{csv_path}' does not exist.")
        return

    conn = get_connection()
    cursor = conn.cursor()

    try:
        sqls = None
        copy_sql = None

        if table == "feedbacks_feedback":
            sqls = """
            CREATE TABLE IF NOT EXISTS public.feedbacks_feedback (
                id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                content text NOT NULL,
                date timestamp with time zone NOT NULL,
                title character varying(200) NOT NULL,
                user_id integer NOT NULL,
                CONSTRAINT feedbacks_feedback_pkey PRIMARY KEY (id),
                CONSTRAINT feedbacks_feedback_user_id_fk_auth_user_id 
                    FOREIGN KEY (user_id) REFERENCES public.auth_user (id) ON DELETE CASCADE
            );
            """
            copy_sql = """
                COPY feedbacks_feedback(id, content, date, title, user_id)
                FROM STDIN
                WITH (FORMAT csv, HEADER true, DELIMITER ',');
            """

        elif table == "posts_post":
            sqls = """
            CREATE TABLE IF NOT EXISTS public.posts_post(
                    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
                    title character varying(200) COLLATE pg_catalog."default" NOT NULL,
                    content text COLLATE pg_catalog."default" NOT NULL,
                    issue_date timestamp with time zone NOT NULL,
                    status character varying(50) COLLATE pg_catalog."default" NOT NULL,
                    user_id integer NOT NULL,
                    stuff_id bigint,
                    type character varying(50) COLLATE pg_catalog."default" NOT NULL,
                    due_date timestamp with time zone,
                    reward boolean NOT NULL DEFAULT false,
                    CONSTRAINT posts_post_pkey PRIMARY KEY (id),
                    CONSTRAINT posts_post_stuff_id_3f4521a3_fk_stuffs_stuff_id FOREIGN KEY (stuff_id)
                        REFERENCES public.stuffs_stuff (id) MATCH SIMPLE
                        ON UPDATE NO ACTION
                        ON DELETE NO ACTION
                        DEFERRABLE INITIALLY DEFERRED,
                    CONSTRAINT posts_post_user_id_a4f40dc7_fk_auth_user_id FOREIGN KEY (user_id)
                        REFERENCES public.auth_user (id) MATCH SIMPLE
                        ON UPDATE NO ACTION
                        ON DELETE NO ACTION
                        DEFERRABLE INITIALLY DEFERRED
                );
                """
            copy_sql = """
                COPY posts_post(id, title, content, issue_date, status, user_id, stuff_id, type, due_date, reward)
                FROM STDIN
                WITH (FORMAT csv, HEADER true, DELIMITER ',', QUOTE '"', ESCAPE '"');
            """

        elif table == "stuffs_stuff":
            sqls = """
                CREATE TABLE IF NOT EXISTS public.stuffs_stuff
                (
                    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
                    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
                    type character varying(50) COLLATE pg_catalog."default" NOT NULL,
                    description text COLLATE pg_catalog."default" NOT NULL,
                    location character varying(100) COLLATE pg_catalog."default" NOT NULL,
                    missing_date timestamp with time zone NOT NULL,
                    user_id integer NOT NULL,
                    photo_main character varying(100) COLLATE pg_catalog."default",
                    district character varying(50) COLLATE pg_catalog."default" NOT NULL,
                    CONSTRAINT stuffs_stuff_pkey PRIMARY KEY (id),
                    CONSTRAINT stuffs_stuff_user_id_07f9efd7_fk_auth_user_id FOREIGN KEY (user_id)
                        REFERENCES public.auth_user (id) MATCH SIMPLE
                        ON UPDATE NO ACTION
                        ON DELETE NO ACTION
                        DEFERRABLE INITIALLY DEFERRED
                );
                        """
            copy_sql = """
                        COPY stuffs_stuff(id, name, type, description, location, missing_date, user_id, photo_main, district)
                        FROM STDIN
                        WITH (FORMAT csv, HEADER true, DELIMITER ',', QUOTE '"', ESCAPE '"');
                    """
        elif table == "comments_comment":
                    sqls = """
                        CREATE TABLE IF NOT EXISTS public.comments_comment
                        (
                            id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
                            content text COLLATE pg_catalog."default" NOT NULL,
                            date timestamp with time zone NOT NULL,
                            post_id bigint NOT NULL,
                            user_id integer NOT NULL,
                            CONSTRAINT comments_comment_pkey PRIMARY KEY (id),
                            CONSTRAINT comments_comment_post_id_96a9ac05_fk_posts_post_id FOREIGN KEY (post_id)
                                REFERENCES public.posts_post (id) MATCH SIMPLE
                                ON UPDATE NO ACTION
                                ON DELETE NO ACTION
                                DEFERRABLE INITIALLY DEFERRED,
                            CONSTRAINT comments_comment_user_id_a1db4881_fk_auth_user_id FOREIGN KEY (user_id)
                                REFERENCES public.auth_user (id) MATCH SIMPLE
                                ON UPDATE NO ACTION
                                ON DELETE NO ACTION
                                DEFERRABLE INITIALLY DEFERRED
                        );
                                """
                    copy_sql = """
                                COPY comments_comment(id, content, date, post_id, user_id)
                                FROM STDIN
                                WITH (FORMAT csv, HEADER true, DELIMITER ',', QUOTE '"', ESCAPE '"');
                            """

        elif table == "auth_user":
                sqls = """
                CREATE TABLE IF NOT EXISTS public.auth_user
                    (
                        id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
                        password character varying(128) COLLATE pg_catalog."default" NOT NULL,
                        last_login timestamp with time zone,
                        is_superuser boolean NOT NULL,
                        username character varying(150) COLLATE pg_catalog."default" NOT NULL,
                        first_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
                        last_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
                        email character varying(254) COLLATE pg_catalog."default" NOT NULL,
                        is_staff boolean NOT NULL,
                        is_active boolean NOT NULL,
                        date_joined timestamp with time zone NOT NULL,
                        CONSTRAINT auth_user_pkey PRIMARY KEY (id),
                        CONSTRAINT auth_user_username_key UNIQUE (username)
                    );
                    """
                copy_sql = """
                    COPY auth_user(id, password, last_login, is_superuser, username,first_name,last_name,email,is_staff,is_active,date_joined)
                    FROM STDIN
                    WITH (FORMAT csv, HEADER true, DELIMITER ',', QUOTE '"', ESCAPE '"');
                    """

        elif table == "user_messages_user_message":
            sqls = """
            CREATE TABLE IF NOT EXISTS public.user_messages_user_message (
                id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
                content text COLLATE pg_catalog."default" NOT NULL,
                date timestamp with time zone NOT NULL,
                receiver_id integer,
                sender_id integer,
                CONSTRAINT user_messages_user_message_pkey PRIMARY KEY (id),
                CONSTRAINT user_messages_user_message_receiver_id_468dc159_fk_auth_user_id FOREIGN KEY (receiver_id)
                    REFERENCES public.auth_user (id) MATCH SIMPLE
                    ON UPDATE NO ACTION
                    ON DELETE NO ACTION
                    DEFERRABLE INITIALLY DEFERRED,
                CONSTRAINT user_messages_user_message_sender_id_50d6bc50_fk_auth_user_id FOREIGN KEY (sender_id)
                    REFERENCES public.auth_user (id) MATCH SIMPLE
                    ON UPDATE NO ACTION
                    ON DELETE NO ACTION
                    DEFERRABLE INITIALLY DEFERRED
            );
            """
            copy_sql = """
                COPY user_messages_user_message(id, content, date, receiver_id, sender_id)
                FROM STDIN
                WITH (FORMAT csv, HEADER true, DELIMITER ',');
            """

        if sqls and copy_sql:
            cursor.execute(sqls)

            with open(csv_path, "r", encoding="utf-8-sig") as f:
                cursor.copy_expert(copy_sql, f)

            conn.commit()
            print(f"Successfully imported '{csv_path}' into table!")

            query = pg_sql.SQL("SELECT * FROM {table};").format(table=pg_sql.Identifier(table))
            cursor.execute(query)

            for row in cursor.fetchall():
                print(row)
        else:
            print(f"Table choice '{table}' is not implemented for import.")

    except Exception as e:
        conn.rollback()
        print(f"An error occurred: {e}")

    finally:
        cursor.close()
        conn.close()




def export_data(table, output_path):
    conn = get_connection()
    cursor = conn.cursor()
    copy_sql = None

    try:
        if table == "feedbacks_feedback":
            copy_sql = """
                COPY (
                    SELECT id, content, date, title, user_id 
                    FROM feedbacks_feedback
                ) TO STDOUT WITH (FORMAT csv, HEADER true, DELIMITER ',');
            """

        elif table == "posts_post":
            copy_sql = """
                COPY (
                    SELECT id, title, content, issue_date, status, user_id, stuff_id, type, due_date, reward 
                    FROM posts_post
                ) TO STDOUT WITH (FORMAT csv, HEADER true, DELIMITER ',');
            """

        elif table == "stuffs_stuff":
            copy_sql = """
                COPY (
                    SELECT id, name, type, description, location, missing_date, user_id, photo_main, district
                    FROM stuffs_stuff
                ) TO STDOUT WITH (FORMAT csv, HEADER true, DELIMITER ',');
            """
        elif table == "comments_comment":
            copy_sql = """
                COPY (
                    SELECT id, content, date, post_id, user_id
                    FROM comments_comment
                ) TO STDOUT WITH (FORMAT csv, HEADER true, DELIMITER ',');
            """
                    
        elif table == "auth_user":
            copy_sql = """
                COPY (
                    SELECT id, password, last_login, is_superuser, username,first_name,last_name,email,is_staff,is_active,date_joined
                    FROM auth_user
                ) TO STDOUT WITH (FORMAT csv, HEADER true, DELIMITER ',');
            """

        elif table == "user_messages_user_message":
            copy_sql = """
                COPY (
                    SELECT id, content, date, receiver_id, sender_id 
                    FROM user_messages_user_message
                ) TO STDOUT WITH (FORMAT csv, HEADER true, DELIMITER ',');
            """

        if copy_sql:
            with open(output_path, "w", encoding="utf-8") as f:
                cursor.copy_expert(copy_sql, f)
            print(f"Successfully exported data to '{output_path}'!")
        else:
            print(f"Table choice '{table}' is not implemented for export.")

    except Exception as e:
        print(f"An error occurred during export: {e}")

    finally:
        cursor.close()
        conn.close()






def delete_all_data(table):
    conn = None
    try:
        if table:
            conn = get_connection()
            cursor = conn.cursor()

            query = pg_sql.SQL("DELETE FROM {table};").format(
                table=pg_sql.Identifier(table)
            )
            cursor.execute(query)

            conn.commit()
            print(f"Successfully deleted all data from table: {table}")

            cursor.close()
        else:
            print("Table name cannot be empty.")

    except Exception as e:
        if conn:
            conn.rollback()
        print(f"An error occurred during deletion: {e}")

    finally:
        if conn:
            conn.close()





def delete_data(table, col, data):
    conn = None
    try:
        if table:
            conn = get_connection()
            cursor = conn.cursor()

            query = pg_sql.SQL("DELETE FROM {table} WHERE {col} = %s;").format(
                table=pg_sql.Identifier(table), col=pg_sql.Identifier(col)
            )
            cursor.execute(query, (data,))

            conn.commit()
            print(f"Successfully deleted data '{data}' from {table}.{col}")
            cursor.close()
        else:
            print("Table choice cannot be empty.")

    except Exception as e:
        if conn:
            conn.rollback()
        print(f"An error occurred during deletion: {e}")

    finally:
        if conn:
            conn.close()


def main_menu():
    print("==============================================================")
    print("||......................................____...............|| ")
    print("||.7.\\^v.^............................./    \\ .............|| ")
    print("||vN:Y:/:|>>..........................| | |  |.............|| ")
    print("||7:|.Y:://r..........................|l W  r| ............|| ")
    print("||.K.l;|:///>...................... _-||    ||--__  .......|| ")
    print("L|_V_wi/LV_l..................... / \\====  ====y  \\........|| ")
    print("___________]=====================/   \\---Y----/    \\=========")
    print("    |  |  /                     |     \\  |   /     |l         ")
    print("    |  | |              _________\\____ \\-+--/    ,/|l         ")
    print("_________|______________\\             \\__V_/    /__|l_________")
    print("_________________________\\    c[]-     \\++/__-/`_______________")
    print("__________________________\\_____________V_____________________")
    print("______________________________________________________________")

    print("Please select table you want import/export")
    print(
        "1. feedback  2.post  3.stuff  4.comment  5.user  6.user_messages  7.exit"
    )
    num = input().strip()
    table = ""

    if num == "1":
        table = "feedbacks_feedback"
    elif num == "2":
        table = "posts_post"
    elif num == "3":
        table = "stuffs_stuff"
    elif num == "4":
        table = "comments_comment"
    elif num == "5":
        table = "auth_user"
    elif num == "6":
        table = "user_messages_user_message"
    elif num == "7":
        return
    else:
        print("Invalid choice, returning to menu.")
        return

    print("------------------------------------------------------------")
    print("1.  import CSV to database")
    print("2.  export csv")
    print("3.  delete all data")
    print("4.  delete specific data")
    print("5.  exit")
    print("------------------------------------------------------------")

    choice = input("select: ").strip()

    if choice == "1":
        csv_path = input("please import CSV path: ").strip()
        if not csv_path:
            csv_path = f"{table}.csv"
        import_data(table, csv_path)

    elif choice == "2":
        output_path = input("please export CSV path: ").strip()
        if not output_path:
            output_path = f"{table}.csv"
        export_data(table, output_path)

    elif choice == "3":
        delete_all_data(table)

    elif choice == "4":
        col = input("please input column name: ").strip()
        data = input("please input data: ").strip()
        delete_data(table, col, data)

    elif choice == "5":
        return
    else:
        print("Invalid option.")

    again = input("\n continue? (y/n): ").strip().lower()
    if again == "y":
        main_menu()


if __name__ == "__main__":
    main_menu()