# Generated by Django 5.2 on 2026-08-22 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('user_messages', '0002_remove_user_message_sender_user_message_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sender',
        ),
    ]
