# Generated by Django 5.2 on 2026-08-22 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_sender'),
        ('user_messages', '0003_remove_user_message_user_user_message_sender_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receiver',
        ),
    ]
