# Generated by Django 5.2 on 2026-08-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='missing_date',
            field=models.DateTimeField(),
        ),
    ]
