# Generated by Django 5.2 on 2026-08-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0002_alter_stuff_missing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='photo_main',
            field=models.ImageField(blank=True, default='https://picsum.photos/300/200', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
