# Generated by Django 5.2 on 2026-08-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0003_stuff_photo_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='photo_main',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
